// <auto-generated />
using System;
using Kuroko.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kuroko.Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20231003161439_Reports")]
    partial class Reports
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kuroko.Database.Entities.Guild.GuildEntity", b =>
                {
                    b.Property<decimal>("Id")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("Kuroko.Database.Entities.Guild.ModLogEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("DeletedMessages")
                        .HasColumnType("boolean");

                    b.Property<bool>("EditedMessages")
                        .HasColumnType("boolean");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("Join")
                        .HasColumnType("boolean");

                    b.Property<bool>("Leave")
                        .HasColumnType("boolean");

                    b.Property<decimal>("LogChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId")
                        .IsUnique();

                    b.ToTable("GuildModLogs");
                });

            modelBuilder.Entity("Kuroko.Database.Entities.Guild.ReportHandler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("ReportsEntityId")
                        .HasColumnType("integer");

                    b.Property<decimal>("RoleId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("ReportsEntityId");

                    b.ToTable("ReportHandler");
                });

            modelBuilder.Entity("Kuroko.Database.Entities.Guild.ReportsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("RecordMessages")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ReportCategoryId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("TranscriptsChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId")
                        .IsUnique();

                    b.ToTable("GuildReports");
                });

            modelBuilder.Entity("Kuroko.Database.Entities.Guild.RoleRequestEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId")
                        .IsUnique();

                    b.ToTable("GuildRoleRequests");
                });

            modelBuilder.Entity("Kuroko.Database.Entities.UlongEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ModLogEntityId")
                        .HasColumnType("integer");

                    b.Property<int?>("RoleRequestEntityId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("ModLogEntityId");

                    b.HasIndex("RoleRequestEntityId");

                    b.ToTable("UlongEntity");
                });

            modelBuilder.Entity("Kuroko.Database.Entities.User.UserEntity", b =>
                {
                    b.Property<decimal>("Id")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Kuroko.Database.Entities.Guild.ModLogEntity", b =>
                {
                    b.HasOne("Kuroko.Database.Entities.Guild.GuildEntity", "Guild")
                        .WithOne("ModLog")
                        .HasForeignKey("Kuroko.Database.Entities.Guild.ModLogEntity", "GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Kuroko.Database.Entities.Guild.ReportHandler", b =>
                {
                    b.HasOne("Kuroko.Database.Entities.Guild.ReportsEntity", null)
                        .WithMany("ReportHandlers")
                        .HasForeignKey("ReportsEntityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Kuroko.Database.Entities.Guild.ReportsEntity", b =>
                {
                    b.HasOne("Kuroko.Database.Entities.Guild.GuildEntity", "Guild")
                        .WithOne("Reports")
                        .HasForeignKey("Kuroko.Database.Entities.Guild.ReportsEntity", "GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Kuroko.Database.Entities.Guild.RoleRequestEntity", b =>
                {
                    b.HasOne("Kuroko.Database.Entities.Guild.GuildEntity", "Guild")
                        .WithOne("RoleRequest")
                        .HasForeignKey("Kuroko.Database.Entities.Guild.RoleRequestEntity", "GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Kuroko.Database.Entities.UlongEntity", b =>
                {
                    b.HasOne("Kuroko.Database.Entities.Guild.ModLogEntity", null)
                        .WithMany("IgnoredChannelIds")
                        .HasForeignKey("ModLogEntityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Kuroko.Database.Entities.Guild.RoleRequestEntity", null)
                        .WithMany("RoleIds")
                        .HasForeignKey("RoleRequestEntityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Kuroko.Database.Entities.Guild.GuildEntity", b =>
                {
                    b.Navigation("ModLog");

                    b.Navigation("Reports");

                    b.Navigation("RoleRequest");
                });

            modelBuilder.Entity("Kuroko.Database.Entities.Guild.ModLogEntity", b =>
                {
                    b.Navigation("IgnoredChannelIds");
                });

            modelBuilder.Entity("Kuroko.Database.Entities.Guild.ReportsEntity", b =>
                {
                    b.Navigation("ReportHandlers");
                });

            modelBuilder.Entity("Kuroko.Database.Entities.Guild.RoleRequestEntity", b =>
                {
                    b.Navigation("RoleIds");
                });
#pragma warning restore 612, 618
        }
    }
}
